# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mortyverse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Kingfisher', '~> 7.0'
	pod 'RxSwift', '6.7.1'
    	pod 'RxCocoa', '6.7.1'
	pod 'Moya', '~> 15.0'
	pod 'Moya/RxSwift', '~> 15.0'
  # Pods for Mortyverse

  target 'MortyverseTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.7.1'
    pod 'RxTest', '6.7.1'
  end

  target 'MortyverseUITests' do
    # Pods for testing
  end

end
